apiVersion: v1
kind: PersistentVolume
metadata:
  name: malarkey-db-volume
  labels:
    type: local
    app: malarkey
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/malarkey/postgresql