apiVersion: apps/v1
kind: Deployment
metadata:
  name: malarkey
  labels:
    app: malarkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malarkey
  template:
    metadata:
      labels:
        app: malarkey
    spec:
      volumes:
        - name: crt-volume
          secret:
            secretName: malarkey-cert          
      containers:
      - name: malarkey
        image: docker.io/library/malarkey:1.0.5
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-malarkey
        volumeMounts:
          - name: crt-volume
            readOnly: true
            mountPath: "/crts"              
        env:
        - name: UI__HostingBasePath
          value: malarkey
        - name: Integration__ServerBasePath
          value: https://eutonies.com/malarkey
        - name: Integration__PublicKeyFile
          value: /crts/malarkey.crt
        - name: Persistence__Db__ConnectionString
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: dbconn
        - name: Application__SigningCertificate__CertificatePassword
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certsignpassword
        - name: Application__HostingCertificate__CertificatePassword
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certhostpassword
        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__SourceType
          value: Path
        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__CertificateDiskPath
          value: malarkey.pfx
        - name: Integration__Microsoft__AzureAd__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretmicrosoft
        - name: Integration__Facebook__Identity__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretfacebook
        - name: Integration__Google__Identity__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretgoogle
        - name: Integration__Spotify__Identity__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretspotify
