apiVersion: apps/v1
kind: Deployment
metadata:
  name: malarkey
  labels:
    app: malarkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malarkey
  template:
    metadata:
      labels:
        app: malarkey
    spec:
      volumes:
        - name: crt-volume
          secret:
            secretName: malarkey-certs
        - name: malarkeyconfig
          configMap: 
            name: malarkey
            items:
              - key: "appsettings"
                path: "appsettings.production.json"
      containers:
      - name: malarkey
        image: docker.io/suneroenne/malarkey:1.0.1
        ports:
        - containerPort: 8080
          name: http-malarkey
        env:
        - name: Application__SigningCertificate__CertificatePassword
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certpasssigning
        - name: Application__HostingCertificate__CertificatePassword
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certpasshosting

        - name: Integration__Facebook__Identity__ClientId
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: idpfacebookclientid
        - name: Integration__Facebook__Identity__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: idpfacebookclientsecret
        - name: Integration__Microsoft__Identity__ClientId
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: idpmicrosoftclientid
        - name: Integration__Microsoft__AzureAd__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: idpmicrosoftclientsecret
        - name: Integration__Google__Identity__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: idpgoogleclientsecret

        - name: Kestrel__Endpoints__Https__Certificate__Password
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certpasshosting

        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__SourceType
          value: Path
        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__CertificateDiskPath
          value: /crt-volume/malarkey.pfx

        volumeMounts:
                - name: crt-volume
                  readOnly: true
                  mountPath: "/crt-volume"
                - name: malarkeyconfig
                  mountPath: "/config"
                  readOnly: true
