apiVersion: apps/v1
kind: Deployment
metadata:
  name: malarkey
  labels:
    app: malarkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malarkey
  template:
    metadata:
      labels:
        app: malarkey
    spec:
      volumes:
        - name: crt-volume
          secret:
            secretName: malarkey-cert          
      containers:
      - name: malarkey
        image: docker.io/library/malarkey:1.0.70
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-malarkey
        volumeMounts:
          - name: crt-volume
            readOnly: true
            mountPath: "/crts"              
        env:
        - name: UI__HostingBasePath
          value: malarkey
        - name: Application__Certificate__CertificateFileName
          value: /crts/malarkey.base64.pfx
        - name: Application__Certificate__CertificatePassword
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: certpassword
        - name: Integration__ServerBasePath
          value: https://eutonies.com/malarkey
        - name: Persistence__Db__ConnectionString
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: dbconn
        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__SourceType
          value: Path
        - name: Integration__Microsoft__AzureAd__ClientCertificates__0__CertificateDiskPath
          value: malarkey.pfx
        - name: Integration__Microsoft__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretmicrosoft
        - name: Integration__Facebook__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretfacebook
        - name: Integration__Google__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretgoogle
        - name: Integration__Spotify__ClientSecret
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: clientsecretspotify
        - name: Integration__Email__ApiToken
          valueFrom:
            secretKeyRef:
              name: malarkey-secrets
              key: emailapitoken
        - name: Integration__Email__VerifyEmailUrl
          value: https://eutonies.com/malarkey/verify-email