apiVersion: v1
kind: Service
metadata:
  name: malarkey-postgres
spec:
  type: NodePort
  selector:
    app: malarkey-postgres
  ports:
    - port: 5432
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: malarkey-db
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31432
      name: svc-malarkey-postgres
