apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malarkey-db-volume-claim
  labels:
    app: malarkey
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi