name: .NET build

on:
  workflow_dispatch:
  push:  

jobs:
  define-version-number:
    name: Calculate SemVer
    runs-on: ubuntu-24.04
    outputs:
      package-version: ${{ steps.version_step.outputs.majorMinorPatch }}
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true
    - name: Determine SemVer
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.1.3
    
  build-and-publish:
    permissions:
      packages: write # for pushing GitHub Nuget packages

    name: Build & Deploy
    runs-on: windows-2025
    needs: [ define-version-number ]
    env:
      packageversion: ${{ needs.define-version-number.outputs.package-version }}
      packageid: Malarkey.Client
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: .NET Build & Pack
      shell: pwsh
      run: |
        dotnet build Malarkey.Abstractions/Malarkey.Abstractions.csproj -c Release
        dotnet build Malarkey.API/Malarkey.API.csproj -c Release
        dotnet build Malarkey.Application/Malarkey.Application.csproj -c Release
        dotnet build Malarkey.Client/Malarkey.Client.csproj -c Release
        dotnet build Malarkey.Integration/Malarkey.Integration.csproj -c Release
        dotnet build Malarkey.Persistence/Malarkey.Persistence.csproj -c Release
        dotnet build Malarkey.Security/Malarkey.Security.csproj -c Release
        dotnet build Malarkey.UI/Malarkey.UI.csproj -c Release

        dotnet pack Malarkey.Abstractions/Malarkey.Abstractions.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.API/Malarkey.API.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.Application/Malarkey.Application.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.Client/Malarkey.Client.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.Integration/Malarkey.Integration.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.Persistence/Malarkey.Persistence.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.Security/Malarkey.Security.csproj -c Release --artifacts-path ./dist
        dotnet pack Malarkey.UI/Malarkey.UI.csproj -c Release --artifacts-path ./dist
    - name: Publish to Nuget package repository
      shell: pwsh
      env:
        actionsuser: ${{ secrets.EUTONIES_GITHUB_ACTIONS_USER }}
      run: |
        dotnet nuget add source --username $Env:actionsuser --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/Eutonies/index.json"
        $packageFolder = "./dist/package/release"
        $vers = $Env:packageversion
        dotnet nuget push "${packageFolder}/Malarkey.Abstractions.${vers}.nupkg" --source "github"
        dotnet nuget push "${packageFolder}/Malarkey.Client.${vers}.nupkg" --source "github"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Abstractions
      id: upload-release-asset_abstractions 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./dist/package/release/Malarkey.Abstractions.${{ needs.define-version-number.outputs.package-version }}.nupkg
        asset_name: Malarkey.Abstractions.nupkg
        asset_content_type: application/zip
    - name: Upload Client
      id: upload-release-asset_client
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./dist/package/release/Malarkey.Client.${{ needs.define-version-number.outputs.package-version }}.nupkg
        asset_name: Malarkey.Client.nupkg
        asset_content_type: application/zip
