name: .NET build

on:
  workflow_dispatch:
  push:  

jobs:
  define-version-number:
    name: Calculate SemVer
    runs-on: ubuntu-24.04
    outputs:
      package-version: ${{ steps.version_step.outputs.majorMinorPatch }}
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true
    - name: Determine SemVer
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.1.3
    
  build-and-publish:
    permissions:
      packages: write # for pushing GitHub Nuget packages

    name: Build & Deploy
    runs-on: windows-2025
    needs: [ define-version-number ]
    env:
      packageversion: ${{ needs.define-version-number.outputs.package-version }}
      packageid: Malarkey.Client
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: .NET Build & Pack
      shell: pwsh
      env:
        PKGVERS: ${{ needs.define-version-number.outputs.package-version }}
      run: |
        dotnet build Malarkey.Abstractions/Malarkey.Abstractions.csproj -c Release
        dotnet build Malarkey.Client/Malarkey.Client.csproj -c Release
        dotnet build Malarkey.Integration/Malarkey.Integration.csproj -c Release
        dotnet pack Malarkey.Abstractions/Malarkey.Abstractions.csproj -c Release --artifacts-path ./dist -p:AssemblyVersion=$Env:PKGVERS -p:Version=$Env:PKGVERS
        dotnet pack Malarkey.Client/Malarkey.Client.csproj -c Release --artifacts-path ./dist -p:AssemblyVersion=$Env:PKGVERS -p:Version=$Env:PKGVERS
        dotnet pack Malarkey.Integration/Malarkey.Integration.csproj -c Release --artifacts-path ./dist -p:AssemblyVersion=$Env:PKGVERS -p:Version=$Env:PKGVERS

    - name: Publish to Nuget package repository
      shell: pwsh
      env:
        actionsuser: ${{ secrets.EUTONIES_GITHUB_ACTIONS_USER }}
        galleryuser: ${{ secrets.EUTONIES_NUGET_GALLERY_USER }}
        gallerykey: ${{ secrets.EUTONIES_NUGET_GALLERY_APIKEY }}
        GH_TOKEN: ${{ github.token }}
      run: |
        dotnet nuget add source --username $Env:actionsuser --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/Eutonies/index.json"
        $packageFolder = "./dist/package/release"
        $vers = $Env:packageversion
        $versionName = "v$Env:packageversion"
        gh release create $versionName "${packageFolder}/Malarkey.Abstractions.${vers}.nupkg" "${packageFolder}/Malarkey.Client.${vers}.nupkg" "${packageFolder}/Malarkey.Integration.${vers}.nupkg"
        gh release upload $versionName "${packageFolder}/Malarkey.Abstractions.${vers}.nupkg" "${packageFolder}/Malarkey.Client.${vers}.nupkg" "${packageFolder}/Malarkey.Integration.${vers}.nupkg"

        dotnet nuget push "${packageFolder}/Malarkey.Abstractions.${vers}.nupkg" --source "github"
        dotnet nuget push "${packageFolder}/Malarkey.Client.${vers}.nupkg" --source "github"
        dotnet nuget push "${packageFolder}/Malarkey.Integration.${vers}.nupkg" --source "github"

        dotnet nuget push "${packageFolder}/Malarkey.Abstractions.${vers}.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key $Env:gallerykey
        dotnet nuget push "${packageFolder}/Malarkey.Client.${vers}.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key $Env:gallerykey
        dotnet nuget push "${packageFolder}/Malarkey.Integration.${vers}.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key $Env:gallerykey

